# Generated by Django 4.2.30 on 2026-05-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='available_slots',
            field=models.TextField(blank=True, help_text="e.g. 'Mon 7-9 PM, Wed 7-9 PM'"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='response_rate',
            field=models.PositiveSmallIntegerField(default=0, help_text='Percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timeline_milestones',
            field=models.JSONField(blank=True, default=list, help_text='List of {"date": "...", "text": "..."}'),
        ),
    ]
