# Generated by Django 4.2.30 on 2026-05-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='admin_dashb_action_62d131_idx',
            old_name='admin_dashb_action_739831_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='admin_dashb_user_id_bc7aee_idx',
            old_name='admin_dashb_user_id_3f5210_idx',
        ),
    ]
